version: '2'
services:
  curl:
    image: curlimages/curl:latest
    networks:
      - o11y
    command: "-v minio:9000/minio/health/live"
networks:
  o11y:
    name: o11y
    driver: bridge
    external: true
